### ISSUE TITLE
error on compilation  line 33 

### ISSUE THREAD

**Issue by zeplaz** [Sosoyan/lgt_depth#1]
line 33: "AtUniverse* universe = AiRenderSessionGetUniverse(render_session);"
this line does not compile "render_session" is not defined.
from looking at do in docs i was able to do 
"AtUniverse* universe = AiNodeGetUniverse(node);" which will give you universe from the node. not an expert on this though.

**Comment by sosoyan** [comment]
Which Arnold version are you compiling against, as the code was made to work against 7.2.1.1?
